theme: jekyll-theme-minimal
logo: https://github.com/josbernd/josbernd.github.io/blob/main/logofinal.png
title: Test fuer eine Website
description: Hier koennen wir versuchen eine einfache Website aufzubauen.
